#!/bin/sh
# "Poor man's profiler" using Elfutils stack program - http://poormansprofiler.org/

nsamples="$1"
sleeptime="$2"
pid="$3"

# On Debian, elfutils stack is called eu-stack:
stack="$(which eu-stack || which stack)"
sleep="$(which sleep || echo sleep)"

shift
shift
shift

for x in $(seq 1 "$nsamples"); do
   "$stack" -p "$pid" "$@"
   "$sleep" "$sleeptime"
done
