#!/usr/bin/env ruby

# The MIT License (MIT)
#
# Copyright (c) 2014 Gabriel Corona
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Remove some crap from HTMl snippets.

require "nokogiri"

if (ARGV[0])
  html = File.read(ARGV[0])
else
  html = $stdin.read
end
doc = Nokogiri::HTML::DocumentFragment.parse html

# Remove 'style':
doc.css("*[style]").each do |node|
  style = node.attribute("style")
  node.remove_attribute("style")
  $stderr.puts "Removed style: #{style}\n"
end

# Remove useless span:
doc.css("span").each do |span|
  $stderr.puts "Unwrapping span: #{span}\n"
  span.children.each do |x|
    span.before(x)
  end
  span.remove
end

# Split paragraphs on <br/>:
doc.css("p > br").each do |br|
  p = br.parent

  # Clone
  new_p = p.document.create_element("p")
  p.children.take_while{ |x| x!=br }.each do |x|
    new_p.add_child x
  end
  p.before(new_p)

  br.remove
end

# Remove empty paragraphs:
doc.css("p").each do |node|
  if node.element_children.empty? && /\A *\z/.match(node.inner_text)
    node.remove
  end
end

print doc.to_html
