#!/usr/bin/env python3

import sys
import json
import yaml

if len(sys.argv) < 2:
    data = json.load(sys.stdin)
else:
    with open(sys.argv[1], "rt") as f:
        data = json.load(f)

sys.stdout.write(yaml.dump(data))
