#!/usr/bin/env python3

import sys
import json
import yaml

if len(sys.argv) < 2:
    data = yaml.safe_load(sys.stdin)
else:
    with open(sys.argv[1], "rt") as f:
        data = yaml.safe_load(f)

sys.stdout.write(json.dumps(data))
