#!/usr/bin/env ruby

require 'safe_yaml/load'
require 'json'

if ARGV.length==0
  data = SafeYAML.load(STDIN)
else
  File.open ARGV[0] do |f|
    data = SafeYAML.load(f)
  end
end

$stdout.set_encoding "UTF-8"
$stdout.puts JSON.pretty_generate(data)
