#!/usr/bin/env ruby

require 'safe_yaml/load'
require 'json'

if ARGV.length==0
  data = YAML.load_documents(STDIN)
else
  File.open ARGV[0] do |f|
    data = YAML.load_documents(f)
  end
end

$stdout.set_encoding "UTF-8"
data.each do |x|
  # TODO, Use UTF-8
  $stdout.print "\x1e" + JSON.generate(x) + "\n" unless x.nil?
end
