#!/usr/bin/env python3

# The MIT License (MIT)
#
# Copyright (c) 2016 Gabriel Corona
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

"""
Summary
-------

Launch a child process by passing file descriptors using the systemd API.

Keywords: DMTF, ASF RMCP, DASH, AMT, IPMI.

Usage
-----
socket-activation --socket INET DGRAM udp --bind ::1 5353 -- ./dnsfwd --connect-tcp 127.0.01:53 --loglevel 8

TODO
----
* UNIX socket support
* TUN support
* FIFO support
* ulimit
* Options:
  * TCP_NODELAY
  * SO_BINDTODEVICE
  * SO_DONTROUTE
  * etc.
"""

import socket
import sys
import os

def parse_family(family):
    """
    Parse an addres family (INET, INET6, LOCAL, etc.)
    """
    if not type(family) == str:
        return family
    try:
        return int(family)
    except ValueError:
        return getattr(socket, "AF_" + family)

def parse_type(socktype):
    """
    Parse a socket type (STREAM, DGRAM, SEQPACKET, etc.).
    """
    if not type(socktype) == str:
        return type
    try:
        return int(socktype)
    except ValueError:
        return getattr(socket, "SOCK_" + socktype)

def parse_proto(family, proto):
    """
    Parse a protocol (TCP, tcp, L2CAP, etc.)
    """
    if not type(proto) == str:
        return proto
    try:
        return int(proto)
    except ValueError:
        pass
    if family == socket.AF_CAN:
        return getattr(socket, "CAN_" + proto)
    if family == socket.AF_BLUETOOTH:
        return getattr(socket, "BTPROTO_" + proto)
    if family == socket.AF_INET or family == socket.AF_INET6:
        try:
            return getattr(socket, "IPPROTO_" + proto)
        except AttributeError:
            return socket.getprotobyname(proto)
    raise ValueError

class SocketDefinition:
    """
    Description of a socket we want to create.
    """

    def __init__(self, family=socket.AF_INET, socktype=socket.SOCK_STREAM, proto=0):
        self._family = family
        self._socktype = socktype
        self._proto = proto
        self._bind = None
        self.name = "unknown"

    def bind(self, addr, port):
        # TODO, handle non INET as well
        res = socket.getaddrinfo(addr, port,
                                 family=self._family,
                                 type=self._socktype, proto=self._proto)
        self._bind = res[0][4]

    def create(self):
        """
        Create the socket.
        """
        s = socket.socket(self._family, self._socktype, self._proto)
        if self._bind != None:
            s.bind(self._bind)
        s.set_inheritable(True)
        return s

user = None
group = None
defs = []

# Parse arguments:
i = 1
while i < len(sys.argv):
    arg = sys.argv[i]
    if arg == "--":
        i = i + 1
        break
    if arg == "--name":
        defs[-1].name = sys.argv[i+1]
        i = i + 2
    elif arg == "--socket":
        (family, socktype, proto) = sys.argv[i+1:i+4]
        i = i + 4
        family = parse_family(family)
        socktype = parse_type(socktype)
        proto = parse_proto(family, proto)
        defs.append(SocketDefinition(family, socktype, proto))
    elif arg == "--bind":
      defs[-1].bind(sys.argv[i + 1], sys.argv[i + 2])
      i = i + 3
    elif arg == "--user":
        user = sys.argv[i + 1]
        i = i + 2
    elif arg == "--group":
        group = sys.argv[i + 1]
        i = i + 2
    else:
        raise NotImplementedError
exec_argv = sys.argv[i:]

# Create the sockets:
for (i,definition) in enumerate(defs):
    s = definition.create()
    # Move it at the suitable place:
    if s.fileno() != i + 3:
        os.dup2(s.fileno(), i + 3)
        s.close()
    else:
        s.detach()

# Change user and group:
uid = None
gid = None
if group != None:
    import grp
    try:
        gid = int(group)
    except ValueError:
        gid = grp.getgrnam(group).gr_gid
if user != None:
    import pwd
    try:
        uid = int(user)
    except ValueError:
        ent = pwd.getpwnam(user)
        uid = ent.pw_uid
        if gid == None:
            gid = ent.pw_gid
if gid != None:
    os.setgid(gid)
if uid != None:
    os.setuid(uid)

# Prepare the environment:
os.environ["LISTEN_FDS"] = str(len(defs))
os.environ["LISTEN_PID"] = str(os.getpid())
os.environ["LISTEN_FDNAMES"] = ":".join([ definition.name for definition in defs ])

# Exec:
os.execvp(exec_argv[0], exec_argv)
