#!/usr/bin/python 

# Open an image (ISO) using udisks2 and open nautilus.
# (Nautilus has some UI in order to 'eject' the image.)
# Dependencies: python, python-dbus, nautilus, udisks2

import dbus
import os
import sys

fd = os.open(sys.argv[1], os.O_RDONLY)
bus = dbus.SystemBus()
manager = bus.get_object("org.freedesktop.UDisks2",
                        "/org/freedesktop/UDisks2/Manager")
loop = dbus.Interface(manager, "org.freedesktop.UDisks2.Manager").LoopSetup(fd, {})
loop = bus.get_object("org.freedesktop.UDisks2", loop)
path = dbus.Interface(loop, "org.freedesktop.UDisks2.Filesystem").Mount({})
dbus.Interface(loop, "org.freedesktop.UDisks2.Loop").SetAutoclear(True, {})

if os.fork()==0:
    os.execlp("nautilus", "nautilus", "--", path)
sys.exit(0)

