#!/usr/bin/env sh
# Parse a second #! line.
# This line is passed to 'sh -c'.
# This allow more flexibility.

# Example usage:
#!/usr/bin/env shbang
#SHBANG exec mutt -F "$@"

shbang_run() {

    local command
    local shbang

    command="$1"
    shbang="$(head -n2 -- "$command"| tail -n1)"

    case "$shbang" in
        \#SHBANG\ *)
          shbang="${shbang#\#SHBANG\ }"
          exec sh -c "${shbang}" "$@"
          ;;
        *)
          echo "SHBANG script not recognized";
          exit 127
          ;;
    esac
}

shbang_run "$@"
